### ISSUE TITLE
How can I modify the uploaded file and save the uploaded content?

### ISSUE THREAD

**Issue by xuliwen0919** [xuliwen0919/xlw-demo-1#3]

**Comment by kannpai** [comment]
After you push to the github, the files will be uploaded.

**Comment by xuliwen0919** [comment]
> After you push to the github, the files will be uploaded.

haha, I want to ask how to modify the file I have already upload!!

**Comment by xuliwen0919** [comment]
> After you push to the github, the files will be uploaded.

To preserve a continuous process of change

**Comment by XiaohanSyrena** [comment]
Maybe you could add a branch and waiting for our feedback.
